version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://<username>:<password>@<supabase_host>:<port>/<database_name>
      - SECRET_KEY=<your_secret_key>
      - SUPABASE_URL=<your_supabase_url>
      - SUPABASE_ANON_KEY=<your_supabase_anon_key>
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: <username>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <database_name>
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: